# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(429, 558)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 30, 370, 480))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(157, 81,             78, 219), stop:1 rgba(95, 60, 61, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(214, 124,             124, 219), stop:1 rgba(214, 124, 124, 219));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(214, 124, 124, 219);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.Main_BG = QtWidgets.QLabel(self.widget)
        self.Main_BG.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.Main_BG.setStyleSheet("border-image:url(:/Img/background -- R.png);\n"
"border-radius: 20px;\n"
"")
        self.Main_BG.setText("")
        self.Main_BG.setObjectName("Main_BG")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.label_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9),  stop:0.375 rgba(0, 0, 0, 50),  stop:0.835227 rgba(0, 0, 0, 75));\n"
"border-radius: 20px;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Dark_BG = QtWidgets.QLabel(self.widget)
        self.Dark_BG.setGeometry(QtCore.QRect(40, 60, 280, 390))
        self.Dark_BG.setStyleSheet("background-color:rgba(0,0,0,100);\n"
"border-radius:15px;\n"
"")
        self.Dark_BG.setText("")
        self.Dark_BG.setObjectName("Dark_BG")
        self.Login_txt = QtWidgets.QLabel(self.widget)
        self.Login_txt.setGeometry(QtCore.QRect(120, 90, 131, 40))
        font = QtGui.QFont()
        font.setFamily("White On Black")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Login_txt.setFont(font)
        self.Login_txt.setStyleSheet("color:rgba(255,255,255,210);")
        self.Login_txt.setObjectName("Login_txt")
        self.Username_LE = QtWidgets.QLineEdit(self.widget)
        self.Username_LE.setGeometry(QtCore.QRect(80, 165, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Username_LE.setFont(font)
        self.Username_LE.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255); \n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px;")
        self.Username_LE.setObjectName("Username_LE")
        self.Password_LE = QtWidgets.QLineEdit(self.widget)
        self.Password_LE.setGeometry(QtCore.QRect(80, 230, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password_LE.setFont(font)
        self.Password_LE.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255); \n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px;")
        self.Password_LE.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password_LE.setObjectName("Password_LE")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(80, 310, 200, 40))
        font = QtGui.QFont()
        font.setFamily("SEGA LOGO FONT")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButon:{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(157, 81,             78, 219), stop:1 rgba(95, 60, 61, 226));\n"
"    color: rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(214, 124,             124, 219), stop:1 rgba(214, 124, 124, 219));\n"
"}\n"
" \n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(214, 124, 124, 219);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.Forgot_txt = QtWidgets.QLabel(self.widget)
        self.Forgot_txt.setGeometry(QtCore.QRect(80, 360, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.Forgot_txt.setFont(font)
        self.Forgot_txt.setStyleSheet("color:rgba(255, 255, 255, 140);")
        self.Forgot_txt.setObjectName("Forgot_txt")
        self.Reset_txt = QtWidgets.QLabel(self.widget)
        self.Reset_txt.setGeometry(QtCore.QRect(130, 380, 91, 16))
        self.Reset_txt.setStyleSheet("color:rgba(6, 126, 255, 140);")
        self.Reset_txt.setObjectName("Reset_txt")
        self.Main_BG.raise_()
        self.label_2.raise_()
        self.Dark_BG.raise_()
        self.Login_txt.raise_()
        self.Forgot_txt.raise_()
        self.Reset_txt.raise_()
        self.Password_LE.raise_()
        self.pushButton.raise_()
        self.Username_LE.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Login_txt.setText(_translate("Form", "LOG IN"))
        self.Username_LE.setPlaceholderText(_translate("Form", "User Name"))
        self.Password_LE.setPlaceholderText(_translate("Form", "Password "))
        self.pushButton.setText(_translate("Form", "Log In"))
        self.Forgot_txt.setText(_translate("Form", "Forgot you Username or Password? "))
        self.Reset_txt.setText(_translate("Form", "Reset Password"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
